dist: xenial

language: python

# sudo false implies containerized builds
sudo: required

branches:
  only:
  - master

python:
  - 3.7

env:
  global:
    # package name for test invocation
    - PACKAGENAME="acrobotics"

before_install:
# Here we download miniconda and install the dependencies
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda create -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- pip install -r requirements.txt

install:
- python setup.py install

script:
- pytest --cov=$PACKAGENAME

after_success:
- codecov
